node:
    image: hanzel/docker-sloppy
    ports:
        - "8000:8000"
    links:
        - redis

redis:
    image: redis
    command: redis-server --appendonly yes
    expose:
        - "6379"
    volumes:
        - .:/data